// AUTO-GENERATED by illustrations/export_storefront.py — do not edit.
// The published illustration feed from the Winsome Illustration Library.
import type {Illustration} from "~/lib/illustrations";

export const FEED_ILLUSTRATIONS: Illustration[] = [
  {
    "id": "floral/hydrangea",
    "subject": "Hydrangea",
    "niche": "Floral",
    "tags": [
      "florals",
      "flr-hydrangea-hs",
      "flr-hydrangea-mg",
      "flr-hydrangea-wc",
      "heritage sketch",
      "hs"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-hydrangea-hs.png",
      "modern-graphic": "/illustrations/flr-hydrangea-mg.svg",
      "watercolor": "/illustrations/flr-hydrangea-wc.png"
    }
  },
  {
    "id": "floral/lily-bouquet",
    "subject": "Lily Bouquet",
    "niche": "Floral",
    "tags": [
      "bouquet",
      "floral",
      "florals",
      "flr-lily-bouquet-hs",
      "flr-lily-bouquet-mg",
      "flr-lily-bouquet-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-lily-bouquet-hs.png",
      "modern-graphic": "/illustrations/flr-lily-bouquet-mg.svg",
      "watercolor": "/illustrations/flr-lily-bouquet-wc.png"
    }
  },
  {
    "id": "floral/lily-bud",
    "subject": "Lily Bud",
    "niche": "Floral",
    "tags": [
      "floral",
      "florals",
      "flower",
      "flr-lily-bud-hs",
      "flr-lily-bud-mg",
      "flr-lily-bud-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-lily-bud-hs.png",
      "modern-graphic": "/illustrations/flr-lily-bud-mg.svg",
      "watercolor": "/illustrations/flr-lily-bud-wc.png"
    }
  },
  {
    "id": "floral/long-stem-lily",
    "subject": "Long-Stem Lily",
    "niche": "Floral",
    "tags": [
      "floral",
      "florals",
      "flower",
      "flr-long-stem-lily-hs",
      "flr-long-stem-lily-mg",
      "flr-long-stem-lily-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-long-stem-lily-hs.png",
      "modern-graphic": "/illustrations/flr-long-stem-lily-mg.svg",
      "watercolor": "/illustrations/flr-long-stem-lily-wc.png"
    }
  },
  {
    "id": "floral/long-stem-rose",
    "subject": "Long-Stem Rose",
    "niche": "Floral",
    "tags": [
      "floral",
      "florals",
      "flower",
      "flr-long-stem-rose-hs",
      "flr-long-stem-rose-mg",
      "flr-long-stem-rose-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-long-stem-rose-hs.png",
      "modern-graphic": "/illustrations/flr-long-stem-rose-mg.svg",
      "watercolor": "/illustrations/flr-long-stem-rose-wc.png"
    }
  },
  {
    "id": "floral/rose-bouquet",
    "subject": "Rose Bouquet",
    "niche": "Floral",
    "tags": [
      "bouquet",
      "floral",
      "florals",
      "flr-rose-bouquet-hs",
      "flr-rose-bouquet-mg",
      "flr-rose-bouquet-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-rose-bouquet-hs.png",
      "modern-graphic": "/illustrations/flr-rose-bouquet-mg.svg",
      "watercolor": "/illustrations/flr-rose-bouquet-wc.png"
    }
  },
  {
    "id": "floral/rose-bud",
    "subject": "Rose Bud",
    "niche": "Floral",
    "tags": [
      "floral",
      "florals",
      "flower",
      "flr-rose-bud-hs",
      "flr-rose-bud-mg",
      "flr-rose-bud-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-rose-bud-hs.png",
      "modern-graphic": "/illustrations/flr-rose-bud-mg.svg",
      "watercolor": "/illustrations/flr-rose-bud-wc.png"
    }
  },
  {
    "id": "floral/single-lily",
    "subject": "Single Lily",
    "niche": "Floral",
    "tags": [
      "floral",
      "florals",
      "flower",
      "flr-single-lily-hs",
      "flr-single-lily-mg",
      "flr-single-lily-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-single-lily-hs.png",
      "modern-graphic": "/illustrations/flr-single-lily-mg.svg",
      "watercolor": "/illustrations/flr-single-lily-wc.png"
    }
  },
  {
    "id": "floral/single-rose",
    "subject": "Single Rose",
    "niche": "Floral",
    "tags": [
      "floral",
      "florals",
      "flower",
      "flr-single-rose-hs",
      "flr-single-rose-mg",
      "flr-single-rose-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/flr-single-rose-hs.png",
      "modern-graphic": "/illustrations/flr-single-rose-mg.svg",
      "watercolor": "/illustrations/flr-single-rose-wc.png"
    }
  },
  {
    "id": "maps/florida-outline",
    "subject": "Florida Outline",
    "niche": "Maps",
    "tags": [
      "florida",
      "heritage sketch",
      "hs",
      "map",
      "map-florida-outline-hs",
      "map-florida-outline-mg"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-florida-outline-hs.png",
      "modern-graphic": "/illustrations/map-florida-outline-mg.svg",
      "watercolor": "/illustrations/map-florida-outline-wc.png"
    }
  },
  {
    "id": "maps/florida-with-heart",
    "subject": "Florida with Heart",
    "niche": "Maps",
    "tags": [
      "florida",
      "heart",
      "heritage sketch",
      "hs",
      "map",
      "map-florida-with-heart-hs"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-florida-with-heart-hs.png",
      "modern-graphic": "/illustrations/map-florida-with-heart-mg.svg",
      "watercolor": "/illustrations/map-florida-with-heart-wc.png"
    }
  },
  {
    "id": "maps/florida-with-palm",
    "subject": "Florida with Palm",
    "niche": "Maps",
    "tags": [
      "florida",
      "heritage sketch",
      "hs",
      "map",
      "map-florida-with-palm-hs",
      "map-florida-with-palm-mg"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-florida-with-palm-hs.png",
      "modern-graphic": "/illustrations/map-florida-with-palm-mg.svg",
      "watercolor": "/illustrations/map-florida-with-palm-wc.png"
    }
  },
  {
    "id": "maps/globe",
    "subject": "Globe",
    "niche": "Maps",
    "tags": [
      "heritage sketch",
      "hs",
      "map",
      "map-globe-hs",
      "map-globe-mg",
      "map-globe-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-globe-hs.png",
      "modern-graphic": "/illustrations/map-globe-mg.svg",
      "watercolor": "/illustrations/map-globe-wc.png"
    }
  },
  {
    "id": "maps/texas-outline",
    "subject": "Texas Outline",
    "niche": "Maps",
    "tags": [
      "heritage sketch",
      "hs",
      "map",
      "map-texas-outline-hs",
      "map-texas-outline-mg",
      "map-texas-outline-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-texas-outline-hs.png",
      "modern-graphic": "/illustrations/map-texas-outline-mg.svg",
      "watercolor": "/illustrations/map-texas-outline-wc.png"
    }
  },
  {
    "id": "maps/texas-with-heart",
    "subject": "Texas with Heart",
    "niche": "Maps",
    "tags": [
      "heart",
      "heritage sketch",
      "hs",
      "map",
      "map-texas-with-heart-hs",
      "map-texas-with-heart-mg"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-texas-with-heart-hs.png",
      "modern-graphic": "/illustrations/map-texas-with-heart-mg.svg",
      "watercolor": "/illustrations/map-texas-with-heart-wc.png"
    }
  },
  {
    "id": "maps/texas-with-star",
    "subject": "Texas with Star",
    "niche": "Maps",
    "tags": [
      "heritage sketch",
      "hs",
      "map",
      "map-texas-with-star-hs",
      "map-texas-with-star-mg",
      "map-texas-with-star-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-texas-with-star-hs.png",
      "modern-graphic": "/illustrations/map-texas-with-star-mg.svg",
      "watercolor": "/illustrations/map-texas-with-star-wc.png"
    }
  },
  {
    "id": "maps/vintage-world-map",
    "subject": "Vintage World Map",
    "niche": "Maps",
    "tags": [
      "compass",
      "heritage sketch",
      "hs",
      "map",
      "map-vintage-world-map-hs",
      "map-vintage-world-map-mg"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-vintage-world-map-hs.png",
      "modern-graphic": "/illustrations/map-vintage-world-map-mg.svg",
      "watercolor": "/illustrations/map-vintage-world-map-wc.png"
    }
  },
  {
    "id": "maps/world-map",
    "subject": "World Map",
    "niche": "Maps",
    "tags": [
      "heritage sketch",
      "hs",
      "map",
      "map-world-map-hs",
      "map-world-map-mg",
      "map-world-map-wc"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/map-world-map-hs.png",
      "modern-graphic": "/illustrations/map-world-map-mg.svg",
      "watercolor": "/illustrations/map-world-map-wc.png"
    }
  },
  {
    "id": "sports/crossed-lacrosse-sticks",
    "subject": "Crossed Lacrosse Sticks",
    "niche": "Sports",
    "tags": [
      "crest",
      "heritage sketch",
      "hs",
      "lacrosse",
      "mg",
      "modern graphic"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-crossed-lacrosse-sticks-hs.png",
      "modern-graphic": "/illustrations/spt-crossed-lacrosse-sticks-mg.svg",
      "watercolor": "/illustrations/spt-crossed-lacrosse-sticks-wc.png"
    }
  },
  {
    "id": "sports/crossed-tennis-rackets",
    "subject": "Crossed Tennis Rackets",
    "niche": "Sports",
    "tags": [
      "crest",
      "heritage sketch",
      "hs",
      "mg",
      "modern graphic",
      "rackets"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-crossed-tennis-rackets-hs.png",
      "modern-graphic": "/illustrations/spt-crossed-tennis-rackets-mg.svg",
      "watercolor": "/illustrations/spt-crossed-tennis-rackets-wc.png"
    }
  },
  {
    "id": "sports/lacrosse-stick",
    "subject": "Lacrosse Stick",
    "niche": "Sports",
    "tags": [
      "heritage sketch",
      "hs",
      "lacrosse",
      "mg",
      "modern graphic",
      "sports"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-lacrosse-stick-hs.png",
      "modern-graphic": "/illustrations/spt-lacrosse-stick-mg.svg",
      "watercolor": "/illustrations/spt-lacrosse-stick-wc.png"
    }
  },
  {
    "id": "sports/lacrosse-stick-ball",
    "subject": "Lacrosse Stick & Ball",
    "niche": "Sports",
    "tags": [
      "ball",
      "heritage sketch",
      "hs",
      "lacrosse",
      "mg",
      "modern graphic"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-lacrosse-stick-ball-hs.png",
      "modern-graphic": "/illustrations/spt-lacrosse-stick-ball-mg.svg",
      "watercolor": "/illustrations/spt-lacrosse-stick-ball-wc.png"
    }
  },
  {
    "id": "sports/pickleball",
    "subject": "Pickleball",
    "niche": "Sports",
    "tags": [
      "heritage sketch",
      "hs",
      "mg",
      "modern graphic",
      "sports",
      "spt-pickleball-hs"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-pickleball-hs.png",
      "modern-graphic": "/illustrations/spt-pickleball-mg.svg",
      "watercolor": "/illustrations/spt-pickleball-wc.png"
    }
  },
  {
    "id": "sports/tennis-racket",
    "subject": "Tennis Racket",
    "niche": "Sports",
    "tags": [
      "heritage sketch",
      "hs",
      "mg",
      "modern graphic",
      "racket",
      "sports"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-tennis-racket-hs.png",
      "modern-graphic": "/illustrations/spt-tennis-racket-mg.svg",
      "watercolor": "/illustrations/spt-tennis-racket-wc.png"
    }
  },
  {
    "id": "sports/tennis-racket-ball",
    "subject": "Tennis Racket & Ball",
    "niche": "Sports",
    "tags": [
      "ball",
      "heritage sketch",
      "hs",
      "mg",
      "modern graphic",
      "racket"
    ],
    "assets": {
      "heritage-sketch": "/illustrations/spt-tennis-racket-ball-hs.png",
      "modern-graphic": "/illustrations/spt-tennis-racket-ball-mg.svg",
      "watercolor": "/illustrations/spt-tennis-racket-ball-wc.png"
    }
  }
];
