"""
Master catalog source data — the curated subject lists behind the Winsome
Studio icon library, transcribed + expanded from Daniel & Sydney's brief.

Shape: CATALOG = list of category blocks. Each block:
  {
    "category": validated Category (Lists & Validation tab),
    "subcat": (Name, CODE) — added to Taxonomy Dictionary,
    "theme": Theme / Collection default,
    "audience": ..., "occasion": ..., "season": "", "holiday": "",
    "palette": default WC palette phrase, "products": compatible codes,
    "kw": extra keywords for every subject in the block,
    "subjects": [ (Subject, [variations] or None, detail-or-None), ... ]
  }
Variations None → single default icon. Detail None → builder writes a
category-appropriate brief. Keep names customer-plain; no trademarks.
"""

P_ALL = "NC-FLAT; NC-FOLD; NP; GT; STK; AT; WT; MUG; TOTE"

def S(name, var=None, detail=None):
    return (name, var, detail)

FLOWER_MAJORS = [
    "Rose", "Peony", "Hydrangea", "Tulip", "Daffodil", "Lily", "Magnolia",
    "Sunflower", "Dahlia", "Iris", "Camellia", "Gardenia", "Cherry Blossom",
    "Lavender", "Ranunculus", "Anemone", "Poppy", "Orchid", "Wisteria",
    "Lilac", "Hibiscus", "Marigold", "Chrysanthemum", "Zinnia", "Cosmos",
    "Sweet Pea", "Delphinium", "Foxglove", "Hollyhock", "Snapdragon",
    "Carnation", "Aster", "Bluebell", "Buttercup", "Clematis", "Crocus",
    "Freesia", "Geranium", "Hyacinth", "Jasmine",
]
FLOWER_MINORS = [
    "Lisianthus", "Hellebore", "Amaryllis", "Azalea", "Begonia", "Bird of Paradise",
    "Black-Eyed Susan", "Bleeding Heart", "Bougainvillea", "Calla Lily", "Columbine",
    "Coneflower", "Cornflower", "Daisy", "Dogwood Blossom", "Edelweiss", "Forget-Me-Not",
    "Forsythia", "Fuchsia", "Gerbera Daisy", "Gladiolus", "Heather", "Hibiscus Bud",
    "Honeysuckle", "Impatiens", "Lantana", "Larkspur", "Lily of the Valley", "Lotus",
    "Lupine", "Morning Glory", "Narcissus", "Nasturtium", "Pansy", "Passionflower",
    "Periwinkle", "Petunia", "Phlox", "Plumeria", "Primrose", "Protea",
    "Queen Anne's Lace", "Rhododendron", "Scabiosa", "Statice", "Stephanotis",
    "Stock Flower", "Thistle", "Trillium", "Tuberose", "Verbena", "Violet",
    "Water Lily", "Yarrow", "Zenith Rose",
]
BOTANICALS = [
    "Eucalyptus Sprig", "Olive Branch", "Fern Frond", "Monstera Leaf", "Palm Frond",
    "Ivy Vine", "Boxwood Sprig", "Laurel Sprig", "Cotton Stem", "Wheat Sheaf",
    "Pampas Grass", "Pussy Willow", "Crape Myrtle Branch", "Magnolia Branch",
    "Ginkgo Leaf", "Maple Leaf", "Oak Leaf", "Birch Branch", "Pine Bough",
    "Succulent", "Cactus", "Herb Bundle", "Rosemary Sprig", "Basil Sprig",
    "Mint Sprig", "Sage Sprig", "Thyme Sprig",
]
WREATHS = [
    ("Spring Wreath", "pastel garden blooms, tulips and greenery"),
    ("Summer Wreath", "lush greenery, daisies and wildflowers"),
    ("Fall Wreath", "autumn leaves, wheat, acorns and mums"),
    ("Winter Wreath", "evergreen, pinecones and winter berries"),
    ("Christmas Wreath", "evergreen with red berries, pinecones and a red bow"),
    ("Thanksgiving Wreath", "harvest leaves, mini pumpkins and wheat"),
    ("Halloween Wreath", "autumn twigs, tiny pumpkins and moody foliage"),
    ("St. Patrick's Day Wreath", "shamrocks and soft green ribbon"),
    ("Valentine's Day Wreath", "roses, hearts and blush ribbon"),
    ("Easter Wreath", "spring blossoms, pastel eggs and greenery"),
    ("Mother's Day Wreath", "garden roses, peonies and soft ribbon"),
    ("Fourth of July Wreath", "red, white and blue blooms with ribbon"),
    ("Laurel Wreath", "classic laurel leaves, monogram-ready center"),
    ("Eucalyptus Wreath", "airy eucalyptus stems, modern and fresh"),
]

SPORTS = [
    ("Golf", ["Crossed Golf Clubs", "Golf Tee with Ball", "Golf Flag on Green", "Golf Bag"], "vintage heritage golf clubs matching an antique sporting-goods engraving: EXTREMELY slender straight hickory wood shafts (thin as a walking cane), small compact flat blade-iron heads, and neatly wrapped leather grips — long, elegant, crisply drawn, realistic antique proportions, never thick, chunky, short, or toy-like"),
    ("Tennis", ["Crossed Tennis Rackets", "Tennis Racket with Ball", "Tennis Ball"], "classic tennis equipment"),
    ("Pickleball", ["Crossed Pickleball Paddles", "Pickleball Paddle with Ball"], "pickleball paddle with perforated ball"),
    ("Lacrosse", ["Crossed Lacrosse Sticks", "Lacrosse Stick with Ball"], "netted lacrosse crosse"),
    ("Baseball", ["Baseball Bat and Ball", "Baseball Glove", "Crossed Baseball Bats", "Baseball"], "classic baseball gear"),
    ("Softball", ["Softball and Glove"], None),
    ("Basketball", ["Basketball", "Basketball Hoop"], None),
    ("Football", ["Football", "Goal Posts"], "American football"),
    ("Soccer", ["Soccer Ball", "Soccer Cleat"], None),
    ("Volleyball", ["Volleyball"], None),
    ("Swimming", ["Swim Goggles", "Diving Swimmer"], None),
    ("Running", ["Running Shoe"], None),
    ("Cycling", ["Bicycle", "Road Bike Helmet"], None),
    ("Sailing", ["Sailboat", "Ship's Wheel"], None),
    ("Rowing", ["Crossed Oars", "Rowing Shell"], None),
    ("Skiing", ["Crossed Skis", "Ski Boots", "Chairlift", "Apres Ski Cocoa Mug"], "alpine ski equipment"),
    ("Snowboarding", ["Snowboard"], None),
    ("Ice Skating", ["Figure Skates"], None),
    ("Ice Hockey", ["Crossed Hockey Sticks with Puck", "Hockey Skates"], None),
    ("Equestrian", ["Horse and Rider Jumping", "Riding Helmet and Crop", "Horseshoe", "English Saddle"], "refined equestrian"),
    ("Polo", ["Crossed Polo Mallets", "Polo Player at Gallop"], None),
    ("Croquet", ["Croquet Mallet and Ball"], None),
    ("Badminton", ["Badminton Racket and Shuttlecock"], None),
    ("Squash", ["Squash Racket and Ball"], None),
    ("Table Tennis", ["Ping Pong Paddle and Ball"], None),
    ("Archery", ["Bow and Arrow", "Archery Target"], None),
    ("Fencing", ["Crossed Fencing Foils"], None),
    ("Gymnastics", ["Gymnast on Beam", "Gymnastics Rings"], None),
    ("Cheerleading", ["Pom Poms", "Megaphone"], None),
    ("Dance", ["Ballet Slippers", "Ballerina Silhouette", "Tap Shoes"], None),
    ("Track and Field", ["Winged Track Shoe", "Hurdle"], None),
    ("Wrestling", ["Wrestling Headgear"], None),
    ("Boxing", ["Boxing Gloves"], None),
    ("Martial Arts", ["Karate Belt"], None),
    ("Climbing", ["Carabiner and Rope", "Mountain Summit Flag"], None),
    ("Hiking", ["Hiking Boots", "Trail Sign"], None),
    ("Camping", ["Camp Tent", "Campfire", "Lantern", "S'more"], None),
    ("Surfing", ["Surfboard", "Wave"], None),
    ("Paddleboarding", ["Paddleboard with Paddle"], None),
    ("Kayaking", ["Kayak with Paddle"], None),
    ("Canoeing", ["Canoe"], None),
    ("Water Skiing", ["Water Skis"], None),
    ("Scuba Diving", ["Dive Mask and Snorkel"], None),
    ("Bowling", ["Bowling Pin and Ball"], None),
    ("Billiards", ["Eight Ball and Cue"], None),
    ("Darts", ["Dartboard with Darts"], None),
    ("Skateboarding", ["Skateboard"], None),
    ("Rugby", ["Rugby Ball"], None),
    ("Cricket", ["Cricket Bat and Ball"], None),
    ("Curling", ["Curling Stone and Broom"], None),
    ("Rodeo", ["Cowboy Hat and Lasso", "Bucking Bronco"], None),
]

DOG_BREEDS = [
    "Golden Retriever", "Labrador Retriever", "Goldendoodle", "Labradoodle",
    "French Bulldog", "English Bulldog", "Cavalier King Charles Spaniel",
    "King Charles Spaniel", "Poodle", "Miniature Poodle", "Toy Poodle",
    "Dachshund", "German Shepherd", "Corgi", "Beagle", "Boston Terrier",
    "Yorkshire Terrier", "Shih Tzu", "Maltese", "Havanese", "Bichon Frise",
    "Pug", "Boxer", "Great Dane", "Bernese Mountain Dog", "Saint Bernard",
    "Newfoundland", "Australian Shepherd", "Border Collie", "Shetland Sheepdog",
    "Cocker Spaniel", "Springer Spaniel", "Brittany Spaniel", "Irish Setter",
    "Gordon Setter", "English Setter", "Pointer", "German Shorthaired Pointer",
    "Vizsla", "Weimaraner", "Rhodesian Ridgeback", "Doberman Pinscher",
    "Rottweiler", "Bullmastiff", "Great Pyrenees", "Samoyed", "Siberian Husky",
    "Alaskan Malamute", "Akita", "Shiba Inu", "Chow Chow", "Dalmatian",
    "Whippet", "Greyhound", "Italian Greyhound", "Basset Hound", "Bloodhound",
    "Coonhound", "Foxhound", "Jack Russell Terrier", "Rat Terrier",
    "Fox Terrier", "Scottish Terrier", "West Highland Terrier", "Cairn Terrier",
    "Airedale Terrier", "Bull Terrier", "Staffordshire Terrier", "Chihuahua",
    "Pomeranian", "Papillon", "Pekingese", "Lhasa Apso", "Old English Sheepdog",
    "Sheepadoodle", "Bernedoodle", "Cavapoo", "Cockapoo", "Maltipoo",
    "Schnauzer", "Miniature Schnauzer", "Giant Schnauzer", "Portuguese Water Dog",
    "Wheaten Terrier", "Irish Wolfhound", "Scottish Deerhound", "Borzoi",
    "Afghan Hound", "Saluki", "Basenji", "Shar Pei", "Leonberger",
    "English Mastiff", "Cane Corso", "Belgian Malinois", "Catahoula",
    "Australian Cattle Dog", "Mixed Breed Rescue",
]
CAT_BREEDS = [
    "Maine Coon", "Persian", "Siamese", "Ragdoll", "British Shorthair",
    "Scottish Fold", "Sphynx", "Bengal", "Abyssinian", "Russian Blue",
    "Norwegian Forest Cat", "Siberian", "Burmese", "Birman", "Himalayan",
    "Devon Rex", "Cornish Rex", "American Shorthair", "Exotic Shorthair",
    "Oriental Shorthair", "Tonkinese", "Turkish Angora", "Chartreux",
    "Manx", "Savannah", "Bombay", "Ocicat", "Somali", "Balinese",
    "Egyptian Mau", "Tuxedo Cat", "Orange Tabby", "Grey Tabby", "Calico Cat",
    "Tortoiseshell Cat", "Black Cat", "White Cat",
]
SMALL_PETS = [
    "Rabbit", "Guinea Pig", "Hamster", "Gerbil", "Ferret", "Hedgehog",
    "Iguana", "Bearded Dragon", "Gecko", "Turtle", "Tortoise", "Parakeet",
    "Cockatiel", "Goldfish", "Betta Fish", "Chinchilla",
]

WILD_ANIMALS = [
    "Elephant", "Giraffe", "Lion", "Tiger", "Leopard", "Cheetah", "Zebra",
    "Rhinoceros", "Hippopotamus", "Gorilla", "Chimpanzee", "Orangutan",
    "Panda", "Koala", "Kangaroo", "Sloth", "Anteater", "Armadillo",
    "Bison", "Buffalo", "Moose", "Elk", "Deer", "White-Tailed Deer", "Fawn",
    "Bear", "Grizzly Bear", "Black Bear", "Polar Bear", "Fox", "Red Fox",
    "Arctic Fox", "Wolf", "Coyote", "Raccoon", "Skunk", "Opossum", "Beaver",
    "Otter", "Badger", "Squirrel", "Chipmunk", "Hedgehog", "Porcupine",
    "Mouse", "Meadow Vole", "Bat", "Camel", "Llama", "Alpaca", "Monkey",
    "Lemur", "Red Panda", "Snow Leopard", "Lynx", "Bobcat", "Mountain Lion",
    "Jaguar", "Hyena", "Warthog", "Meerkat", "Gazelle", "Antelope", "Ibex",
    "Mountain Goat", "Bighorn Sheep",
]
FARM_ANIMALS = [
    "Horse", "Pony", "Donkey", "Cow", "Highland Cow", "Calf", "Pig", "Piglet",
    "Sheep", "Lamb", "Goat", "Baby Goat", "Chicken", "Rooster", "Hen with Chicks",
    "Duck", "Duckling", "Goose", "Turkey", "Barn Cat", "Farm Dog",
]
BIRDS = [
    "Cardinal", "Blue Jay", "Robin", "Chickadee", "Goldfinch", "House Finch",
    "Sparrow", "Wren", "Nuthatch", "Tufted Titmouse", "Woodpecker",
    "Red-Headed Woodpecker", "Hummingbird", "Ruby-Throated Hummingbird",
    "Baltimore Oriole", "Eastern Bluebird", "Mockingbird", "Meadowlark",
    "Mourning Dove", "Barn Swallow", "Purple Martin", "Cedar Waxwing",
    "Indigo Bunting", "Painted Bunting", "Scarlet Tanager", "Warbler",
    "Bald Eagle", "Golden Eagle", "Red-Tailed Hawk", "Falcon", "Osprey",
    "Barn Owl", "Great Horned Owl", "Snowy Owl", "Screech Owl", "Raven", "Crow",
    "Magpie", "Pheasant", "Quail", "Partridge", "Grouse", "Wild Turkey",
    "Peacock", "Swan", "Mallard Duck", "Wood Duck", "Canada Goose", "Heron",
    "Great Blue Heron", "Egret", "Crane", "Sandhill Crane", "Flamingo",
    "Pelican", "Seagull", "Sandpiper", "Puffin", "Penguin", "Kingfisher",
    "Toucan", "Parrot", "Macaw", "Cockatoo", "Canary", "Dove with Olive Branch",
    "Stork with Bundle", "Loon", "Chicken Wire Hen", "Nest with Eggs",
]
SEA_LIFE = [
    "Seahorse", "Dolphin", "Whale", "Humpback Whale", "Blue Whale", "Orca",
    "Manatee", "Sea Turtle", "Shark", "Great White Shark", "Hammerhead Shark",
    "Octopus", "Squid", "Jellyfish", "Stingray", "Manta Ray", "Starfish",
    "Sand Dollar", "Sea Urchin", "Crab", "Blue Crab", "Hermit Crab", "Lobster",
    "Shrimp", "Clam", "Oyster with Pearl", "Mussel", "Scallop Shell",
    "Conch Shell", "Nautilus Shell", "Coral", "Seaweed", "Angelfish",
    "Clownfish", "Pufferfish", "Swordfish", "Narwhal", "Seal", "Sea Otter", "Walrus",
]
INSECTS = [
    "Honeybee", "Bumblebee", "Butterfly", "Monarch Butterfly",
    "Swallowtail Butterfly", "Blue Morpho Butterfly", "Dragonfly", "Damselfly",
    "Ladybug", "Firefly", "Grasshopper", "Cricket", "Praying Mantis",
    "Caterpillar", "Snail", "Beetle", "Scarab Beetle", "Stag Beetle",
    "Moth", "Luna Moth", "Cicada", "Ant", "Spider Web with Dew",
]

FISH_SPECIES = [
    "Marlin", "Blue Marlin", "Sailfish", "Swordfish", "Tuna", "Yellowfin Tuna",
    "Mahi Mahi", "Wahoo", "Tarpon", "Bonefish", "Permit", "Redfish", "Snook",
    "Striped Bass", "Largemouth Bass", "Smallmouth Bass", "Walleye", "Northern Pike",
    "Muskie", "Perch", "Crappie", "Bluegill", "Catfish", "Carp", "Rainbow Trout",
    "Brown Trout", "Brook Trout", "Salmon", "King Salmon", "Steelhead",
    "Grouper", "Snapper", "Red Snapper", "Halibut", "Flounder", "Cod", "Barracuda",
]
FISHING_GEAR = [
    "Fly Fishing Rod and Reel", "Fishing Rod and Bobber", "Tackle Box",
    "Fishing Lure", "Fly Fishing Flies", "Fishing Creel", "Landing Net",
    "Waders and Boots", "Fish Hook", "Bass Jumping",
]
HUNTING = [
    "Duck Hunting Decoy", "Mallard in Flight", "Pheasant Hunting", "Flushing Pheasant",
    "Quail Covey", "Wild Turkey Hunting", "Deer Hunting Stand", "Whitetail Buck",
    "Elk Bugling", "Duck Call", "Shotgun Shells", "Hunting Dog on Point",
    "English Pointer on Point", "Labrador with Duck", "Duck Blind", "Antler Shed",
    "Camouflage Cap", "Hunting Lodge Cabin",
]
HOBBIES = [
    ("Mahjong", ["Mahjong Tile", "Mahjong Tile Trio", "Mahjong Rack"], "classic mahjong tiles with bamboo and character motifs"),
    ("Bridge", ["Bridge Card Hand", "Card Suits"], "playing cards fanned"),
    ("Bunco", ["Bunco Dice"], "three dice"),
    ("Bingo", ["Bingo Card with Dauber"], None),
    ("Poker", ["Poker Chips and Cards"], None),
    ("Chess", ["Chess Knight", "Chess Pieces"], None),
    ("Backgammon", ["Backgammon Board"], None),
    ("Dominoes", ["Domino Tiles"], None),
    ("Scrabble Night", ["Letter Tiles"], "wooden letter tiles (generic)"),
    ("Crossword", ["Crossword Grid with Pencil"], None),
    ("Knitting", ["Yarn Ball with Needles", "Knitted Sweater"], None),
    ("Crochet", ["Crochet Hook with Yarn"], None),
    ("Sewing", ["Sewing Machine", "Thread Spools", "Pin Cushion", "Scissors and Thimble"], None),
    ("Quilting", ["Quilt Block", "Patchwork Quilt"], None),
    ("Embroidery", ["Embroidery Hoop with Florals"], None),
    ("Needlepoint", ["Needlepoint Canvas"], None),
    ("Cross Stitch", ["Cross Stitch Sampler"], None),
    ("Pottery", ["Potter's Wheel", "Ceramic Vase"], None),
    ("Painting", ["Paint Palette with Brushes", "Easel with Canvas"], None),
    ("Photography", ["Vintage Camera"], None),
    ("Birdwatching", ["Binoculars", "Field Guide with Binoculars"], None),
    ("Gardening", ["Watering Can", "Garden Trowel and Gloves", "Terracotta Pots", "Seed Packets", "Garden Boots", "Greenhouse"], None),
    ("Beekeeping", ["Beehive", "Bee Skep", "Honey Jar with Dipper"], None),
    ("Baking", ["Rolling Pin", "Whisk and Bowl", "Stand Mixer", "Measuring Spoons"], None),
    ("Cooking", ["Chef's Knife and Board", "Cast Iron Skillet", "Copper Pots"], None),
    ("Grilling", ["BBQ Grill", "Grill Tools"], None),
    ("Wine Tasting", ["Wine Glass and Bottle", "Corkscrew and Cork"], None),
    ("Coffee", ["French Press", "Espresso Cup", "Pour Over"], None),
    ("Tea", ["Teapot with Cup", "Tea Tin"], None),
    ("Reading", ["Stack of Books", "Open Book", "Reading Glasses on Book", "Library Card"], None),
    ("Writing", ["Fountain Pen", "Typewriter", "Wax Seal and Letter"], None),
    ("Music", ["Grand Piano", "Violin", "Acoustic Guitar", "Trumpet", "Cello", "Music Notes", "Vinyl Record Player"], None),
    ("Theater", ["Comedy and Tragedy Masks", "Theater Curtain"], None),
    ("Ballet", ["Pointe Shoes with Ribbon"], None),
    ("Travel Planning", ["Vintage Suitcase", "Passport and Tickets", "Camera and Map"], None),
    ("Puzzles", ["Jigsaw Pieces"], None),
    ("Model Trains", ["Toy Train Engine"], None),
    ("Stargazing", ["Telescope"], None),
    ("Woodworking", ["Hand Plane and Chisel"], None),
    ("Antiquing", ["Antique Clock", "Vintage Key"], None),
    ("Scrapbooking", ["Scrapbook with Photos"], None),
    ("Calligraphy", ["Calligraphy Nib and Ink"], None),
]

STATES = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine",
    "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi",
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
    "Washington", "West Virginia", "Wisconsin", "Wyoming",
]
COUNTRIES = [
    "United States", "Canada", "Mexico", "United Kingdom", "England", "Scotland",
    "Ireland", "Wales", "France", "Italy", "Spain", "Portugal", "Germany",
    "Austria", "Switzerland", "Netherlands", "Belgium", "Denmark", "Sweden",
    "Norway", "Finland", "Iceland", "Greece", "Croatia", "Czech Republic",
    "Poland", "Hungary", "Turkey", "Israel", "Morocco", "Egypt", "South Africa",
    "Kenya", "India", "China", "Japan", "South Korea", "Thailand", "Vietnam",
    "Singapore", "Philippines", "Indonesia", "Australia", "New Zealand",
    "Brazil", "Argentina", "Chile", "Peru", "Colombia", "Costa Rica", "Panama",
    "Bahamas", "Jamaica", "Cuba", "Dominican Republic", "Puerto Rico",
    "Bermuda", "Saudi Arabia", "United Arab Emirates", "Russia", "Ukraine",
]
WORLD_LANDMARKS = [
    ("Eiffel Tower", "Paris"), ("Arc de Triomphe", "Paris"), ("Notre-Dame Cathedral", "Paris"),
    ("Louvre Pyramid", "Paris"), ("Big Ben", "London"), ("Tower Bridge", "London"),
    ("London Eye", "London"), ("Colosseum", "Rome"), ("Leaning Tower of Pisa", "Italy"),
    ("Venice Gondola", "Venice"), ("Trevi Fountain", "Rome"), ("Sagrada Familia", "Barcelona"),
    ("Windmill", "Amsterdam"), ("Brandenburg Gate", "Berlin"), ("Neuschwanstein Castle", "Germany"),
    ("Matterhorn", "Switzerland"), ("Acropolis", "Athens"), ("Santorini Domes", "Greece"),
    ("Hagia Sophia", "Istanbul"), ("Great Pyramid of Giza", "Egypt"), ("Sphinx", "Egypt"),
    ("Taj Mahal", "India"), ("Great Wall of China", "China"), ("Mount Fuji", "Japan"),
    ("Torii Gate", "Japan"), ("Sydney Opera House", "Sydney"), ("Christ the Redeemer", "Rio"),
    ("Machu Picchu", "Peru"), ("Chichen Itza", "Mexico"), ("Moai Statues", "Easter Island"),
    ("Stonehenge", "England"), ("Edinburgh Castle", "Scotland"), ("Cliffs of Moher", "Ireland"),
    ("Petra", "Jordan"), ("Burj Khalifa", "Dubai"), ("Niagara Falls", "North America"),
    ("Grand Canyon", "Arizona"), ("Old Faithful Geyser", "Yellowstone"),
    ("Half Dome", "Yosemite"), ("Mount Rushmore", "South Dakota"),
    ("Statue of Liberty", "New York"), ("Empire State Building", "New York"),
    ("Brooklyn Bridge", "New York"), ("Golden Gate Bridge", "San Francisco"),
    ("Hollywood Sign Hills", "Los Angeles"), ("Space Needle", "Seattle"),
    ("Gateway Arch", "St. Louis"), ("The Alamo", "San Antonio"),
    ("Washington Monument", "Washington DC"), ("US Capitol Dome", "Washington DC"),
    ("White House", "Washington DC"), ("Lincoln Memorial", "Washington DC"),
    ("Liberty Bell", "Philadelphia"), ("Freedom Trail Lantern", "Boston"),
    ("Fenway Green Monster", "Boston"), ("Chicago Bean", "Chicago"),
    ("Willis Tower", "Chicago"), ("French Quarter Balcony", "New Orleans"),
    ("Streetcar", "New Orleans"), ("Nashville Guitar Skyline", "Nashville"),
    ("Country Music Boot", "Nashville"), ("Las Vegas Sign", "Las Vegas"),
    ("Denver Mountains Skyline", "Denver"), ("Charleston Rainbow Row", "Charleston"),
    ("Savannah Oak with Moss", "Savannah"), ("Miami Art Deco Lifeguard Tower", "Miami"),
    ("Aspen Ski Gondola", "Aspen"), ("Napa Vineyard Rows", "Napa Valley"),
    ("Palm Springs Mid-Century House", "Palm Springs"), ("Route 66 Sign", "USA"),
    ("Lighthouse", "Coastal"), ("Cape Cod Lighthouse", "Cape Cod"),
    ("Nantucket Basket", "Nantucket"), ("Adirondack Chair", "Lake"),
    ("Baguette", "Paris"), ("Macaron", "Paris"), ("Croissant", "Paris"),
    ("Beret", "Paris"), ("Vespa Scooter", "Rome"), ("Double-Decker Bus", "London"),
    ("Red Phone Booth", "London"), ("Dutch Tulip Field", "Holland"),
    ("Irish Claddagh", "Ireland"), ("Scottish Tartan Thistle", "Scotland"),
    ("Hot Air Balloon", "Travel"), ("Vintage Airplane", "Travel"),
    ("Cruise Ship", "Travel"), ("Train Locomotive", "Travel"),
    ("Globe on Stand", "Travel"), ("Compass Rose", "Travel"), ("World Map", "Travel"),
]

SWEETS = [
    "Birthday Cake", "Layer Cake", "Wedding Cake", "Bundt Cake", "Cupcake",
    "Sprinkle Cupcake", "Petit Four", "Chocolate Chip Cookie", "Sugar Cookie",
    "Gingerbread Cookie", "Snickerdoodle", "Oatmeal Cookie", "Macaron Stack",
    "Shortbread Cookie", "Linzer Cookie", "Thumbprint Cookie", "Biscotti",
    "Frosted Animal Cookie", "Brownie", "Blondie", "Donut", "Sprinkle Donut",
    "Cinnamon Roll", "Croissant", "Danish Pastry", "Eclair", "Cream Puff",
    "Pie", "Apple Pie", "Cherry Pie", "Pumpkin Pie", "Lemon Meringue Pie",
    "Tart", "Fruit Tart", "Ice Cream Cone", "Ice Cream Sundae", "Popsicle",
    "Milkshake", "Candy Cane", "Lollipop", "Gumball Machine", "Chocolate Box",
    "Chocolate Truffle", "Saltwater Taffy", "Cotton Candy", "S'mores Stack",
]
SAVORY_FRUIT = [
    "Charcuterie Board", "Cheese Wedge", "Baguette Loaf", "Sourdough Loaf",
    "Pretzel", "Bagel", "Pizza Slice", "Pasta Bowl", "Taco", "Avocado Half",
    "Watermelon Slice", "Strawberry", "Strawberries", "Raspberry", "Blueberry Sprig",
    "Blackberry", "Cherry Pair", "Peach", "Pear", "Green Apple", "Red Apple",
    "Orange", "Orange Slice", "Lemon", "Lemon Slice", "Lime", "Grapefruit Half",
    "Pineapple", "Banana", "Grapes", "Grape Vine", "Fig Half", "Pomegranate",
    "Kiwi Slice", "Mango", "Coconut Half", "Olive Sprig", "Tomato", "Heirloom Tomato",
    "Corn on the Cob", "Artichoke", "Radish Bunch", "Carrot Bunch", "Pumpkin",
    "White Pumpkin", "Honey Jar", "Jam Jar", "Picnic Basket",
]
DRINKS = [
    ("Old Fashioned", "an ornate cut-crystal rocks glass of whiskey with ONE large square ice cube and a fresh orange slice resting on the rim (no peel twist)"),
    ("Whiskey Decanter", "cut-crystal decanter with amber whiskey"),
    ("Martini", "classic martini glass with olives on a pick"),
    ("Espresso Martini", "coupe with espresso foam and three coffee beans"),
    ("Margarita", "salt-rimmed margarita glass with lime wheel"),
    ("Aperol Spritz", "wine glass of orange spritz with ice and an orange slice"),
    ("Negroni", "rocks glass with orange slice"),
    ("Champagne Coupe", None), ("Champagne Flute", None),
    ("Champagne Bottle", "bottle with popping cork"),
    ("Champagne Toast", "two flutes clinking"),
    ("Red Wine Glass", None), ("White Wine Glass", None),
    ("Wine Bottle", None), ("Wine Bottle and Glass", None),
    ("Sangria Pitcher", None), ("Mimosa", None),
    ("Bloody Mary", "celery stalk and olive garnish"),
    ("Mint Julep", "silver julep cup with mint sprig"),
    ("Moscow Mule", "copper mug with lime"),
    ("Mojito", None), ("Pina Colada", None), ("Mai Tai", None),
    ("Gin and Tonic", "highball with lime and botanicals"),
    ("Beer Stein", None), ("Craft Beer Pint", None),
    ("Cocktail Shaker", None), ("Bar Cart", "brass bar cart with bottles and glasses"),
    ("Coffee Cup", None), ("Latte Art Cup", None), ("To-Go Coffee", None),
    ("Teacup and Saucer", None), ("Hot Cocoa", "mug with whipped cream and marshmallows"),
    ("Lemonade Pitcher", None), ("Lemonade Glass", None),
    ("Sweet Tea", "mason jar with lemon"), ("Milk Bottle", None),
    ("Smoothie", None), ("Juice Box", None),
]

HOLIDAY_BLOCKS = [
    ("Christmas", "Winter", "Christmas", [
        "Christmas Tree", "Decorated Christmas Tree", "Christmas Ornament",
        "Ornament Trio", "Santa Claus", "Santa Hat", "Mrs. Claus", "Reindeer",
        "Rudolph", "Sleigh with Gifts", "Elf", "Nutcracker", "Toy Soldier",
        "Gingerbread House", "Gingerbread Man", "Candy Cane Heart", "Stocking",
        "Fireplace with Stockings", "Poinsettia", "Mistletoe", "Holly Sprig",
        "Christmas Lights String", "Snow Globe", "Advent Wreath", "Nativity Star",
        "Angel", "Christmas Pudding", "Eggnog", "Ugly Sweater", "Ice Skates on Hook",
        "Sled", "Red Truck with Tree", "Pinecone Trio", "Jingle Bells",
    ]),
    ("Hanukkah", "Winter", "Hanukkah", [
        "Menorah", "Lit Menorah", "Dreidel", "Dreidel Trio", "Star of David",
        "Gelt Coins", "Latkes", "Sufganiyot Donuts", "Kiddush Cup",
    ]),
    ("Thanksgiving", "Fall", "Thanksgiving", [
        "Roast Turkey", "Turkey with Tail Fan", "Cornucopia", "Harvest Table",
        "Pumpkin Pie Slice", "Autumn Leaves Bundle", "Gratitude Banner",
        "Mayflower Ship", "Wishbone", "Fall Harvest Basket",
    ]),
    ("Halloween", "Fall", "Halloween", [
        "Jack-o-Lantern", "Pumpkin Stack", "Friendly Ghost", "Witch Hat",
        "Witch Broom", "Cauldron", "Black Cat Arched", "Bat Trio", "Spider Web",
        "Candy Corn", "Trick or Treat Bucket", "Haunted House", "Skeleton Key",
        "Mummy Wrap Candy", "Owl on Branch Moon",
    ]),
    ("Valentine's Day", "Winter", "Valentine's Day", [
        "Heart", "Heart Trio", "Arrow Through Heart", "Cupid", "Love Letter",
        "Sealed Love Note", "Rose Bouquet Hearts", "Conversation Hearts",
        "Chocolate Heart Box", "XOXO Script", "Lovebirds Pair",
    ]),
    ("Easter", "Spring", "Easter", [
        "Easter Egg", "Painted Egg Trio", "Easter Basket", "Easter Bunny",
        "Bunny with Carrot", "Chick Hatching", "Spring Lamb", "Easter Lily",
        "Egg Hunt Sign", "Carrot Bunch Ribbon",
    ]),
    ("St. Patrick's Day", "Spring", "St. Patrick's Day", [
        "Shamrock", "Four Leaf Clover", "Pot of Gold", "Rainbow with Clouds",
        "Leprechaun Hat", "Horseshoe with Clover", "Celtic Knot",
    ]),
    ("Fourth of July", "Summer", "Fourth of July", [
        "American Flag", "Waving American Flag", "Fireworks Burst", "Sparkler",
        "Uncle Sam Hat", "Patriotic Bunting", "Star Banner", "Liberty Torch",
        "Watermelon Picnic", "BBQ Flag Skewers",
    ]),
    ("New Year's Eve", "Winter", "New Year's Eve", [
        "Champagne Countdown", "Confetti Burst", "Party Hat", "Midnight Clock",
        "Disco Ball", "Cheers Banner",
    ]),
    ("Mother's Day", "Spring", "Mother's Day", [
        "Mama Bird with Nest", "Mother and Child Silhouette", "Best Mom Ribbon",
        "Teacup Bouquet", "Mama Bear with Cub", "Heart Locket",
    ]),
    ("Father's Day", "Summer", "Father's Day", [
        "Best Dad Ribbon", "Necktie", "Bow Tie", "Grill Master Tools",
        "Papa Bear with Cub", "Vintage Wristwatch", "Mustache",
    ]),
]
SEASON_MOTIFS = [
    ("Fall", ["Acorn", "Acorn Pair", "Walnut", "Chestnut", "Maple Leaf Drift",
              "Oak Leaf and Acorn", "Pumpkin Patch Trio", "Hay Bale", "Scarecrow",
              "Cozy Fire Scene", "Plaid Thermos", "Knit Mittens", "Apple Basket",
              "Cider Mug", "Candied Apple", "Sunflower and Wheat", "Harvest Moon"]),
    ("Winter", ["Snowflake", "Snowflake Trio", "Snowman", "Mitten Pair", "Knit Hat",
                "Cozy Scarf", "Cardinal on Snowy Branch", "Evergreen Trio",
                "Pinecone", "Fireside Mug", "Log Cabin in Snow", "Ice Skates"]),
    ("Spring", ["Rain Boots with Flowers", "Umbrella in Rain", "Watering Can Blooms",
                "Bird Nest with Eggs", "Cherry Blossom Branch", "Seedling Sprout",
                "Garden Gate", "Butterfly on Bloom", "Spring Shower Cloud"]),
    ("Summer", ["Sunshine", "Beach Umbrella", "Flip Flops", "Sunglasses",
                "Beach Ball", "Sandcastle", "Popsicle Drip", "Lemonade Stand",
                "Picnic Blanket", "Bicycle with Basket", "Garden Sun Hat",
                "Firefly Jar", "Hammock"]),
]

SPACE = [
    "Crescent Moon", "Full Moon", "Moon and Stars", "Cow Jumping Over the Moon",
    "Shooting Star", "Star Cluster", "North Star", "Constellation Chart",
    "Big Dipper", "Saturn", "Planet Earth", "Mars", "Solar System", "Sun and Rays",
    "Rocket Ship", "Astronaut", "Telescope Night Sky", "Galaxy Swirl",
    "Man in the Moon", "Celestial Sun and Moon",
]
BABY = [
    "Baby Rattle", "Baby Bottle", "Pacifier", "Baby Onesie", "Baby Booties",
    "Knit Booties", "Baby Bib", "Safety Pin", "Rocking Horse", "Teddy Bear",
    "Bunny Lovey", "Baby Carriage", "Stroller", "Crib Mobile", "Cloud Mobile",
    "Rubber Duck", "Wooden Blocks", "ABC Blocks", "Stork Delivery",
    "Bassinet", "High Chair", "Baby Footprints", "Baby Handprint",
    "Nursery Bunting", "Star Nightlight", "Moon Nightlight", "Toy Sailboat",
    "Pull-Along Duck", "Diaper Pin Trio", "Baby Bear", "Baby Elephant with Balloon",
    "Baby Giraffe", "Swaddled Baby", "Twinkle Star", "Lullaby Sheep",
]
CELEBRATION = [
    "Champagne Glasses Clinking", "Confetti Pop", "Balloon Bunch", "Gold Balloon Arch",
    "Birthday Candle Trio", "Party Streamers", "Gift Box with Bow", "Gift Stack",
    "Bunting Banner", "Cake with Candles", "Piñata", "Party Popper",
    "Graduation Cap", "Graduation Cap Toss", "Diploma Scroll", "Graduation Owl",
    "Class Ring", "Anniversary Rings", "Milestone Banner", "Trophy Cup",
    "First Place Ribbon", "Fireworks Celebration",
]
PROFESSIONS = [
    ("Doctor", "stethoscope draped over a white coat"),
    ("Nurse", "nurse cap with medical cross and stethoscope"),
    ("Surgeon", "surgical scrubs cap and mask"),
    ("Dentist", "tooth with toothbrush"),
    ("Veterinarian", "stethoscope with paw print"),
    ("Pharmacist", "mortar and pestle with Rx symbol"),
    ("Therapist", "comfortable chair with notebook"),
    ("Psychologist", "head profile with heart and gears"),
    ("Optometrist", "eyeglasses with eye chart"),
    ("Pediatrician", "stethoscope with teddy bear"),
    ("Lawyer", "scales of justice"),
    ("Judge", "gavel on block"),
    ("Accountant", "calculator with ledger"),
    ("Financier", "bull and bear market pair"),
    ("Banker", "classical bank building"),
    ("Financial Advisor", "growth chart with upward arrow"),
    ("Real Estate Agent", "house with sold sign"),
    ("Architect", "drafting compass with blueprint"),
    ("Engineer", "gear with wrench"),
    ("Software Engineer", "laptop with code brackets"),
    ("Tech Founder", "rocket launching from laptop"),
    ("Data Scientist", "chart with magnifying glass"),
    ("Scientist", "microscope"),
    ("Chemist", "beaker and flask set"),
    ("Biologist", "DNA helix"),
    ("Professor", "mortarboard on books"),
    ("Teacher", "apple on stacked books"),
    ("Librarian", "book cart with glasses"),
    ("Writer", "typewriter with paper"),
    ("Journalist", "press notebook and pen"),
    ("Artist", "palette with brushes"),
    ("Designer", "drafting pen with swatches"),
    ("Photographer", "camera with strap"),
    ("Musician", "treble clef with notes"),
    ("Chef", "chef's hat with crossed utensils"),
    ("Baker", "rolling pin with wheat"),
    ("Sommelier", "wine key with grapes"),
    ("Barista", "portafilter with coffee cup"),
    ("Farmer", "barn with wheat"),
    ("Rancher", "cowboy hat with rope"),
    ("Pilot", "pilot wings badge"),
    ("Flight Attendant", "airplane with heart trail"),
    ("Sea Captain", "captain's hat with anchor"),
    ("Firefighter", "fire helmet with axe"),
    ("Police Officer", "badge with cap"),
    ("Paramedic", "star of life with cross"),
    ("Electrician", "lightning bolt with plug"),
    ("Plumber", "pipe wrench"),
    ("Carpenter", "hammer with saw"),
    ("Mechanic", "crossed wrenches"),
    ("Hairstylist", "shears with comb"),
    ("Makeup Artist", "lipstick with brush"),
    ("Florist", "wrapped flower bouquet"),
    ("Event Planner", "clipboard with celebration checklist"),
    ("Realtor Broker", "key with house keychain"),
    ("Entrepreneur", "lightbulb with briefcase"),
    ("Executive", "briefcase with pen"),
    ("Human Resources", "people network circle"),
    ("Marketer", "megaphone with chart"),
    ("Salesperson", "handshake"),
    ("Astronaut Professional", "space helmet"),
]
MILITARY = [
    "American Flag Folded Triangle", "Dog Tags", "Military Star", "Eagle Crest",
    "Anchor Insignia", "Aviator Wings", "Camouflage Heart", "Yellow Ribbon",
    "Salute Silhouette", "Homecoming Banner", "Military Ball Cap", "Compass Medallion",
]
COLLEGE = [
    ("College Pennant", "customizable felt pennant on a wooden stick — customer picks the color and types the school name inside the pennant shape"),
    ("Pennant Pair Crossed", "two crossed felt pennants, color-changeable"),
    ("Varsity Letter Patch", "chenille varsity letter, color-changeable"),
    ("School Colors Ribbon", "ribbon streamer in customizable school colors"),
    ("Foam Finger", "number-one foam finger, color-changeable"),
    ("Tailgate Tent", "striped tailgate canopy, color-changeable"),
    ("Stadium", "classic college stadium bowl"),
    ("Campus Gate", "brick and iron university gate"),
    ("Campus Bell Tower", "collegiate clock tower"),
    ("Diploma with Ribbon", None),
    ("Sorority Bow", "oversized preppy hair bow, color-changeable"),
    ("Recruitment Roses", "bid day rose bouquet"),
    ("Big Little Hearts", "linked hearts for big and little"),
    ("Greek Row House", "columned sorority house with bunting"),
    ("Dorm Room Pennant Wall", "mini pennant garland"),
]
TEACHER = [
    "Apple on Books", "Polished Red Apple", "Pencil", "Pencil Trio", "Crayons",
    "Chalkboard A-B-C", "Ruler and Pencil Crossed", "Globe on Desk", "School Bus",
    "Alphabet Magnet Letters", "Composition Notebook", "Teacher Tote",
    "Gold Star Sticker", "A-Plus Paper", "Bookworm with Glasses",
    "Reading Corner Rug", "Teacher's Bell", "Best Teacher Ribbon",
]
COASTAL = [
    "Anchor", "Anchor with Rope", "Ship's Wheel", "Sailboat Regatta", "Lighthouse Striped",
    "Life Preserver", "Compass", "Knotted Rope Heart", "Nautical Knot", "Buoy",
    "Rowboat", "Dinghy Oars", "Beach Cottage", "Pier Pilings", "Dock Cleat",
    "Scallop Shell Fan", "Conch on Sand", "Coral Branch", "Driftwood",
    "Message in a Bottle", "Treasure Chest", "Mermaid Tail", "Cape Cod Whale",
    "Nautical Flag A", "Nautical Flag B", "Nautical Flag Pennant String",
    "Crab Bake Pot", "Lobster Trap", "Oyster Trio", "Fish Market Sign",
    "Tide Chart", "Salt Air Banner", "Beach Grass Dune", "Cabana Stripe Umbrella",
]
RELIGIOUS = [
    ("Cross", "Christian", "a simple elegant cross"),
    ("Ornate Cross", "Christian", "a decorative scrollwork cross"),
    ("Cross with Lilies", "Christian", "cross with Easter lilies"),
    ("Praying Hands", "Christian", None),
    ("Dove of Peace", "Christian", "dove with olive branch"),
    ("Angel Wings", "Christian", None),
    ("Bible", "Christian", "open Bible with ribbon marker"),
    ("Rosary", "Christian", None),
    ("First Communion Chalice", "Christian", None),
    ("Baptism Shell", "Christian", "scallop shell with water drops"),
    ("Church Steeple", "Christian", None),
    ("Nativity Scene", "Christian", "simple silhouette nativity"),
    ("Star of David", "Jewish", None),
    ("Menorah Nine Branch", "Jewish", "Hanukkah menorah"),
    ("Menorah Seven Branch", "Jewish", "temple menorah"),
    ("Torah Scroll", "Jewish", None),
    ("Shabbat Candles", "Jewish", "pair of lit candlesticks"),
    ("Challah Loaf", "Jewish", "braided challah"),
    ("Kiddush Wine Cup", "Jewish", None),
    ("Hamsa", "Jewish", "hamsa hand with subtle detail"),
    ("Chai Symbol", "Jewish", None),
    ("Mezuzah", "Jewish", None),
    ("Purim Grogger", "Jewish", "festive Purim noisemaker"),
    ("Hamantaschen", "Jewish", "trio of Purim cookies"),
    ("Passover Seder Plate", "Jewish", None),
]
MOTHER_FATHER = [
    "Mother and Baby Elephant", "Mama Duck with Ducklings", "Mother Hen with Chicks",
    "Mama Bear Family", "Father and Son Fishing", "Dad's Toolbox",
    "Mother's Recipe Box", "Family Tree", "Home Sweet Home House", "Heart Hands",
]
