#!/usr/bin/env python3
"""
The feed: published illustrations → the Hydrogen storefront's Studio picker.

Reads the library, takes only published:true records, groups the 3 styles per
subject, copies the transparent assets into the storefront's public/, and writes
a generated feed module the existing illustration picker consumes. Toggling
"Show on website" in the backend + re-running this updates what shoppers see.
"""
import json, os, shutil
import registry as R

STORE = "/Users/daniel/ClaudeCode/winsome-life-hydrogen"
DEST_ASSETS = os.path.join(STORE, "public", "illustrations")
DEST_FEED = os.path.join(STORE, "app", "data", "illustration-feed.ts")

# our categories → the storefront's niche buckets (picker filter chips)
CAT_NICHE = {"Florals": "Floral", "Sports": "Sports", "Maps": "Maps",
             "Animals": "Botanical", "Games": "Games", "Dogs": "Pets", "Cats": "Pets"}

lib = R.load()
pub = [i for i in lib["items"] if i.get("published")]
groups = {}
for it in pub:
    groups.setdefault((it["category"], it["subject"]), {})[it["style"]] = it

os.makedirs(DEST_ASSETS, exist_ok=True)
entries = []
for (cat, subject), styles in sorted(groups.items()):
    niche = CAT_NICHE.get(cat, cat)
    slug = R.slug(subject)
    assets, tags = {}, set()
    for style, rec in styles.items():
        src = os.path.join(R.GEN, rec["file"])
        ext = os.path.splitext(rec["file"])[1]
        fname = f"{R.CATEGORY_CODE.get(cat, 'x')}-{slug}-{R.STYLE[style]['code']}{ext}"
        shutil.copyfile(src, os.path.join(DEST_ASSETS, fname))
        assets[style] = f"/illustrations/{fname}"
        tags.update(rec.get("keywords", []))
    tags.discard(subject.lower())
    entries.append({"id": f"{niche.lower()}/{slug}", "subject": subject,
                    "niche": niche, "tags": sorted(tags)[:6], "assets": assets})

ts = ('// AUTO-GENERATED by illustrations/export_storefront.py — do not edit.\n'
      '// The published illustration feed from the Winsome Illustration Library.\n'
      'import type {Illustration} from "~/lib/illustrations";\n\n'
      'export const FEED_ILLUSTRATIONS: Illustration[] = '
      + json.dumps(entries, indent=2) + ';\n')
os.makedirs(os.path.dirname(DEST_FEED), exist_ok=True)
with open(DEST_FEED, "w") as f:
    f.write(ts)

niches = sorted({e["niche"] for e in entries})
print(f"Exported {len(entries)} subjects ({len(pub)} illustrations) across niches {niches}")
print(f"  feed  → {DEST_FEED}")
print(f"  assets→ {DEST_ASSETS}")
